#!/usr/bin/env bash

_NEURON_PATH="${HOME}/notes/zettelkasten/"
alias note="neuron -d ${_NEURON_PATH} new -e"
alias notel='vim $(neuron -d ${_NEURON_PATH} search)'

_NEURON_TMUX_SESSION="neuron"
function __attachNeuron() {
    if [ "$TMUX" ]; then
        vim --cmd "cd ${_NEURON_PATH}" "$(neuron -d ${_NEURON_PATH} search)"
    else
        tmux new-session -A -s ${_NEURON_TMUX_SESSION} -c ${_NEURON_PATH} -n neuron "vim \"$(neuron -d ${_NEURON_PATH} search)\""
    fi
}
alias notes='__attachNeuron'
alias n='notes'
